"""
validation/hybrid_validation.py

Builds and validates the OR-hybrid detector (Page-Hinkley (tuned) + DDM
(tuned), validation/detectors_registry.py's OrHybridDetector -- alarms the
moment EITHER constituent alarms) using the exact same two-stage
methodology as everything else in this repo:

  1. Synthetic ground-truth benchmark (same protocol as run_validation.py:
     same scenarios, magnitudes, trial count, and seeds as the existing
     tuned run in validation/results/raw_results_tuned.csv) -- so the
     hybrid's composite score is directly comparable to the existing
     8-detector tuned table in validation/results/tuned/REPORT.md.
  2. Real-data validation (same protocol as live_replay.py) against the
     same local Elec2 / Insects CSVs used throughout this repo -- so the
     hybrid's real-data alarm timing can be compared, sample-for-sample,
     against Page-Hinkley (tuned) and DDM (tuned) alone using the same
     onset-relative-timing approach used in FINAL_VERDICT.md.

This exists because the question "would a hybrid actually be better, or
just my reasoning that it should be" only has a real answer if it's
measured the same way every other detector here was -- not asserted.

Usage (from the repo root):
    python -m validation.hybrid_validation
    python -m validation.hybrid_validation --trials 100 --seed 42
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from validation.detectors_registry import DetectorSpec, HYBRID_NAME, TUNED_CONFIGS, hybrid_registry, tuned_registry
from validation.report import (
    HYBRID_DETECTOR_NAME,
    TUNED_DETECTOR_ORDER,
    compute_summary,
    make_charts,
    write_markdown_report,
)
from validation.run_validation import DEFAULT_SEED, DEFAULT_TRIALS, run_all
from validation.live_replay import run as live_replay_run

assert HYBRID_NAME == HYBRID_DETECTOR_NAME, "hybrid name must match between detectors_registry.py and report.py"


def run_synthetic(trials: int, seed: int, out_dir: Path) -> pd.DataFrame:
    """Same protocol, same trials/seed as the existing tuned run -- so
    these 8 detectors' rows are, sample-for-sample, reproductions of
    raw_results_tuned.csv (the seeding in run_validation.py depends only
    on (seed, scenario, magnitude, trial), never on which detectors are
    in the registry), plus new rows for the hybrid."""
    registry = tuned_registry() + hybrid_registry()
    df = run_all(trials=trials, seed=seed, registry=registry)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "raw_results_hybrid.csv"
    df.to_csv(out_path, index=False)
    print(f"\nWrote {len(df)} rows to {out_path}")
    return df


def report_synthetic(df: pd.DataFrame, trials: int, out_dir: Path) -> pd.DataFrame:
    detector_order = TUNED_DETECTOR_ORDER + [HYBRID_NAME]
    summary = compute_summary(df, detector_order=detector_order)
    out_dir.mkdir(parents=True, exist_ok=True)
    summary.to_csv(out_dir / "summary.csv")
    make_charts(summary, out_dir)
    write_markdown_report(
        summary,
        n_trials=trials,
        out_path=out_dir / "REPORT.md",
        highlight_detector="Page-Hinkley (tuned)",
        title="DriftGuard detector validation — OR-hybrid vs. all 8 tuned detectors (synthetic)",
        generated_by_note=(
            "Generated by `validation/hybrid_validation.py` -- same protocol, trials, and seeds as "
            "`validation/run_validation.py --registry tuned`, plus the OR-hybrid "
            "(Page-Hinkley (tuned) OR DDM (tuned), validation/detectors_registry.py's OrHybridDetector)"
        ),
        all_tuned=True,
    )
    print("\n" + summary.round(3).to_string())
    print(f"\nWrote summary.csv, 4 charts, and REPORT.md to {out_dir}/")
    return summary


def run_real_data(out_dir: Path) -> None:
    """Page-Hinkley (tuned), DDM (tuned), and the hybrid, run against the
    same real local Elec2/Insects CSVs used everywhere else in this repo
    -- a focused 3-way comparison rather than re-running all 8+1, so the
    timeline chart stays readable and directly answers "does the hybrid's
    real-data timing actually improve on its two constituents."""
    focused_registry = [
        DetectorSpec("Page-Hinkley (tuned)", TUNED_CONFIGS["Page-Hinkley"]),
        DetectorSpec("DDM (tuned)", TUNED_CONFIGS["DDM"]),
    ] + hybrid_registry()

    for dataset_name in ("elec2", "insects"):
        live_replay_run(dataset_name, out_dir, registry=focused_registry)


def onset_relative_timing(errors_path: Path, alert_summary_path: Path, onset_estimate: int) -> pd.DataFrame:
    """Same estimation FINAL_VERDICT.md already used for Insects: a
    sustained crossing of baseline + 0.30 on a 200-sample rolling error
    rate. Reproduced here (rather than re-derived) so the hybrid's timing
    is measured against the SAME onset estimate already reported for
    Page-Hinkley/DDM alone, not a freshly re-computed and possibly
    slightly different number."""
    summary = pd.read_csv(alert_summary_path)
    summary["samples_relative_to_onset"] = summary["first_alert_index"] - onset_estimate
    return summary[["detector", "first_alert_index", "samples_relative_to_onset"]].sort_values("first_alert_index")


def _main() -> None:
    parser = argparse.ArgumentParser(description="Build and validate the Page-Hinkley+DDM OR-hybrid detector")
    parser.add_argument("--trials", type=int, default=DEFAULT_TRIALS)
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--out", type=str, default="validation/results")
    parser.add_argument("--skip-real-data", action="store_true", help="Skip the elec2/insects real-data run")
    args = parser.parse_args()

    results_dir = Path(args.out)
    hybrid_dir = results_dir / "hybrid"

    df = run_synthetic(args.trials, args.seed, hybrid_dir)
    report_synthetic(df, args.trials, hybrid_dir)

    if not args.skip_real_data:
        real_out_dir = results_dir / "live_replay" / "hybrid"
        run_real_data(real_out_dir)

        # Insects has the one real dataset with a clean, independently-
        # estimable single drift onset (~14,476) -- see FINAL_VERDICT.md.
        insects_onset = 14476
        timing = onset_relative_timing(
            real_out_dir / "insects_error_stream.csv",
            real_out_dir / "insects_alert_summary.csv",
            insects_onset,
        )
        timing.to_csv(real_out_dir / "insects_onset_relative_timing.csv", index=False)
        print(f"\nInsects onset-relative timing (estimated true onset = sample {insects_onset}):")
        print(timing.to_string(index=False))


if __name__ == "__main__":
    _main()
